extraction:
  cpp:
    configure:
      command:
        - ./autogen.sh
        - ./configure --disable-timesyncd --disable-kdbus --disable-terminal
                      --disable-gtk-doc --disable-manpages --disable-gtk-doc-html
                      --enable-compat-libs --disable-sysusers --disable-ldconfig
                      --enable-lz4 --disable-microhttpd
